# Generated by Django 3.1.6 on 2021-02-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Task Name')),
                ('description', models.TextField(blank=True, db_index=True, null=True, verbose_name='Task Description')),
                ('task_flow', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('In Progress', 'Completed'), ('Completed', 'In Progress'), ('Rejected', 'Rejected')], default='To Do', max_length=30, verbose_name='Task Flow')),
            ],
        ),
    ]
