# Generated by Django 3.1.6 on 2021-02-20 21:35

import datetimeutc.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Request Url')),
                ('body', models.JSONField(null=True, verbose_name='Request Body')),
                ('method', models.CharField(choices=[('post', 'post'), ('get', 'get'), ('put', 'put'), ('patch', 'patch'), ('delete', 'delete')], max_length=30, verbose_name='Request Method')),
                ('header', models.JSONField(verbose_name='Request Header')),
                ('requested_at', datetimeutc.fields.DateTimeUTCField(db_index=True, verbose_name='Request date')),
                ('status_flow', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=30, verbose_name='Request Status Flow')),
                ('status_code', models.CharField(max_length=30, null=True, verbose_name='Request Status Code')),
                ('request_response', models.JSONField(null=True, verbose_name='Request Response')),
            ],
        ),
    ]
