# Generated by Django 3.1.6 on 2021-02-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleRequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='method',
            field=models.CharField(choices=[('post', 'post'), ('get', 'get'), ('put', 'put'), ('delete', 'delete')], max_length=30, verbose_name='Request Method'),
        ),
    ]
